### ISSUE TITLE
Add Jenkins CI

### ISSUE THREAD

**Issue by mbanth** [xmos/lib_locks#20]
Add Jenkins CI support and changes necessary to test on xcore.ai.  See PR #14 for initial work on this issue made by David Atkins when he was still with XMOS.

**Comment by mbanth** [comment]
@ed-xmos, please provide a Story Point value for this issue.  Since Philips will likely use SW locks to enable XVF3800-UA, it seems like a good idea to get this repo running through Jenkins nightly.  Thanks.

**Comment by xhuw** [comment]
#21 resolves this issue. The title says "part 1 of 2", that is not correct. I thought I jenkins wouldn't run before the jenkinsfile was on develop but I was wrong so I managed to get all the tests running in just 1 PR
